version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Host:5001 → Container:5000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rental-network
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-postgres}  # Fallback value
      - DB_NAME=rent_db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/properties"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}  # Fallback value
      POSTGRES_DB: rent_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rental-network
    ports:
      - "5433:5432"  # Host:5433 → Container:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  rental-network:
    driver: bridge