# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rental-network
      environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=rent_db
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: rent_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rental-network
    ports:
      - "5433:5432"

volumes:
  postgres_data:

networks:
  rental-network:
    driver: bridge