# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rental-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rent_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rental-network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  rental-network:
    driver: bridge